import React from "react";
import type { Metadata } from "next";
import { ServiceHeader } from "@/components/services/ServiceHeader";

export const metadata: Metadata = {
    title: "Terms of Service - Megabytes Circuit Systems Ahmedabad",
    description: "Read the Terms of Service of Megabytes Circuit Systems. Understand the terms, manufacturing guidelines, and policies that govern ordering custom PCBs from us.",
};

export default function TermsOfServicePage() {
    const breadcrumbs = [
        { label: "Home", href: "/" },
        { label: "Terms of Service" },
    ];

    return (
        <div className="bg-white min-h-screen pb-20">
            <ServiceHeader
                title="Terms of Service"
                subtitle="The terms, agreements, and policies governing your custom PCB orders."
                badge="Legal Policies"
                breadcrumbs={breadcrumbs}
            />

            <div className="max-w-4xl mx-auto px-6 sm:px-8 py-16 text-slate-700 leading-relaxed space-y-8 font-medium">
                <section>
                    <h2 className="text-2xl font-display font-bold text-secondary mb-4 border-b pb-2">1. Agreement to Terms</h2>
                    <p className="text-sm">
                        By accessing our website and placing custom orders through our online PCB calculator or sales team, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you must not place orders or use our services.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl font-display font-bold text-secondary mb-4 border-b pb-2">2. Custom PCB Ordering and Specifications</h2>
                    <p className="text-sm">
                        All PCB fabrication and assembly orders are custom-made based on the specifications (Gerber files, drill data, BOM) provided by the client. It is the client's responsibility to ensure that all design files match standard industry design guidelines. While Megabytes Circuit Systems performs basic complimentary Design for Manufacturability (DFM) reviews, we are not liable for functional bugs, logic errors, or assembly issues resulting from faulty design inputs.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl font-display font-bold text-secondary mb-4 border-b pb-2">3. Quotations and Pricing</h2>
                    <p className="text-sm">
                        Quotations generated by our online PCB calculator are estimates based on standard material configurations. Megabytes Circuit Systems reserves the right to modify pricing if technical reviews reveal complex routing, custom layer stack-ups, premium substrates (e.g., Rogers, Aluminum core), or custom assembly requirements not captured by the online tool. No modifications will be made without client approval.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl font-display font-bold text-secondary mb-4 border-b pb-2">4. Quality Standards and Warranties</h2>
                    <p className="text-sm">
                        We manufacture PCBs in compliance with standard IPC-A-600 Class 2 quality guidelines. We perform 100% electrical testing and AOI (Automated Optical Inspection) to ensure flawless boards. In case of physical manufacturing defects, clients must report the issues within 14 days of product delivery to qualify for free rework or reprints.
                    </p>
                </section>
            </div>
        </div>
    );
}
